"""Cross-language golden fixture for the MSG_FORWARD_STATES request wire (A3).

The byte streams under tests/fixtures/ are generated by the RUST client
encoder (`encode_forward_states_request` in
hexo-rs/hexo-mcts/src/inference_subprocess.rs, test
`wire_states_golden_fixture`) for fixed positions, and parsed here with the
real server-side parser. This pins encoder and parser to the same bytes:

- wire_states_request.bin       full request frame (6-byte header + body)
- wire_states_legal_hashes.bin  u64 LE per graph: the Rust CLIENT's FNV-1a
                                legal-order hash (compared against the
                                server's rebuilt-legal hashes below)

Regenerate (from the repo root) with:

    CARGO_TARGET_DIR=hexo-rs/target-a3 HEXO_REGEN_WIRE_FIXTURES=1 \
        cargo test -p hexo-mcts --manifest-path hexo-rs/Cargo.toml \
        wire_states_golden_fixture
"""

import io
import struct
from pathlib import Path

import torch

import hexo_rs
from hexo_a0.inference_server import (
    MAGIC,
    MSG_FORWARD,
    MSG_FORWARD_STATES,
    VERSION,
    _prepare_tensors,
    _read_forward_body,
    _read_forward_states_body,
    _states_request_frame,
    _unpack_hexkey,
)

from test_wire_states_parity import _collate_graph_body

FIXTURE_DIR = Path(__file__).parent / "fixtures"

# MUST stay in sync with FIXTURE_MOVES / FIXTURE_POINTS in
# hexo-rs/hexo-mcts/src/inference_subprocess.rs (wire_states_tests).
MOVES = [(1, 0), (0, 1), (2, 0), (1, 1), (-1, 2), (3, -1), (0, -2)]
SNAPSHOT_POINTS = [0, 1, 4, 7]
WIN_LENGTH, PLACEMENT_RADIUS, MAX_MOVES = 6, 8, 200
NODE_DIM = 8  # builder_flags = 0 (no prune / threat / relative)


def _replay(n_moves: int) -> "hexo_rs.GameState":
    config = hexo_rs.GameConfig(WIN_LENGTH, PLACEMENT_RADIUS, MAX_MOVES)
    game = hexo_rs.GameState(config)
    for q, r in MOVES[:n_moves]:
        game.apply_move(q, r)
    return game


def _read_fixture(name: str = "wire_states_request.bin") -> bytes:
    """Read a checked-in golden fixture, FAILING with a clear message when it is
    missing (rather than silently regenerating — the byte pin is meaningless if
    the test can recreate it). The Rust side owns generation; regenerate with
    HEXO_REGEN_WIRE_FIXTURES=1 (see module docstring)."""
    path = FIXTURE_DIR / name
    assert path.exists(), (
        f"missing golden fixture {path}; regenerate with HEXO_REGEN_WIRE_FIXTURES=1 "
        "cargo test -p hexo-mcts wire_states_golden_fixture (the .bin fixtures are "
        "committed — check .gitignore's negation if they vanished)"
    )
    return path.read_bytes()


def test_rust_request_frame_fields_match_replayed_states():
    raw = _read_fixture()
    magic, version, msg_type = struct.unpack("<IBB", raw[:6])
    assert magic == MAGIC
    assert version == VERSION
    assert msg_type == MSG_FORWARD_STATES

    stdin = io.BytesIO(raw[6:])
    (num_graphs, win_length, placement_radius, max_moves,
     builder_flags, node_dim, graphs) = _states_request_frame(stdin)
    assert stdin.read() == b"", "frame must consume the body exactly"

    assert num_graphs == len(SNAPSHOT_POINTS)
    assert win_length == WIN_LENGTH
    assert placement_radius == PLACEMENT_RADIUS
    assert max_moves == MAX_MOVES
    assert builder_flags == 0
    assert node_dim == NODE_DIM

    for (p1_keys, p2_keys, cur, mr, num_legal), k in zip(graphs, SNAPSHOT_POINTS):
        game = _replay(k)

        # Stone sets round-trip through the canonical HexKey packing.
        expected_p1 = sorted(c for c, p in game.placed_stones() if p == "P1")
        expected_p2 = sorted(c for c, p in game.placed_stones() if p == "P2")
        assert sorted(_unpack_hexkey(key) for key in p1_keys) == expected_p1
        assert sorted(_unpack_hexkey(key) for key in p2_keys) == expected_p2
        # The Rust encoder emits keys sorted ascending (deterministic bytes;
        # signed-key order == lexicographic (q, r) order).
        assert list(p1_keys) == sorted(p1_keys)
        assert list(p2_keys) == sorted(p2_keys)

        assert cur == (0 if game.current_player() == "P1" else 1)
        assert mr == game.moves_remaining_this_turn()
        assert num_legal == len(game.legal_moves())


def test_rust_flags7_request_frame_fields_match_replayed_states():
    """Nit D: the SECOND states golden fixture variant carries builder_flags=7
    (prune|threat|relative) and node_dim=11 — the production lean-schema
    cross-check header bytes. Positions/keys/legal counts are flag-independent,
    so they must still round-trip; only the two header bytes differ."""
    raw = _read_fixture("wire_states_request_flags7.bin")
    magic, version, msg_type = struct.unpack("<IBB", raw[:6])
    assert magic == MAGIC
    assert version == VERSION
    assert msg_type == MSG_FORWARD_STATES

    stdin = io.BytesIO(raw[6:])
    (num_graphs, win_length, placement_radius, max_moves,
     builder_flags, node_dim, graphs) = _states_request_frame(stdin)
    assert stdin.read() == b"", "frame must consume the body exactly"

    assert num_graphs == len(SNAPSHOT_POINTS)
    assert (win_length, placement_radius, max_moves) == (
        WIN_LENGTH, PLACEMENT_RADIUS, MAX_MOVES)
    assert builder_flags == 0x07  # prune | threat | relative
    assert node_dim == 11

    for (p1_keys, p2_keys, cur, mr, num_legal), k in zip(graphs, SNAPSHOT_POINTS):
        game = _replay(k)
        expected_p1 = sorted(c for c, p in game.placed_stones() if p == "P1")
        expected_p2 = sorted(c for c, p in game.placed_stones() if p == "P2")
        assert sorted(_unpack_hexkey(key) for key in p1_keys) == expected_p1
        assert sorted(_unpack_hexkey(key) for key in p2_keys) == expected_p2
        assert cur == (0 if game.current_player() == "P1" else 1)
        assert mr == game.moves_remaining_this_turn()
        assert num_legal == len(game.legal_moves())


def test_flags7_server_rebuild_hashes_match_rust_client_hashes():
    """The flags7 variant rebuilt with all three builder flags on must produce
    the SAME per-graph legal-order hashes as the Rust client (legal coords are
    flag-independent, so the flags0 client hashes apply)."""
    raw = _read_fixture("wire_states_request_flags7.bin")
    body, server_hashes = _read_forward_states_body(
        io.BytesIO(raw[6:]), 11,
        prune_empty_edges=True, threat_features=True, relative_stones=True,
    )
    assert body["node_dim"] == 11
    hash_bytes = _read_fixture("wire_states_legal_hashes.bin")
    client_hashes = list(struct.unpack(f"<{len(hash_bytes) // 8}Q", hash_bytes))
    assert list(server_hashes) == client_hashes


# ---------------------------------------------------------------------------
# Graph-mode cross-language golden fixture (TQ2-W1)
# ---------------------------------------------------------------------------

# Dedicated tight-radius config for the graph fixture (the graph wire carries
# full features+edges, so the states fixture's radius-8 positions would bloat
# the committed .bin to ~1 MB). MUST stay in sync with GRAPH_FIXTURE_* in
# hexo-rs/hexo-mcts/src/inference_subprocess.rs (wire_states_tests).
GRAPH_MOVES = [(1, 0), (0, 1), (-1, 1), (1, -1), (0, -1)]
GRAPH_POINTS = [0, 1, 3, 5]
GRAPH_WIN_LENGTH, GRAPH_PLACEMENT_RADIUS, GRAPH_MAX_MOVES = 5, 2, 200


def _replay_graph(n_moves: int) -> "hexo_rs.GameState":
    config = hexo_rs.GameConfig(
        GRAPH_WIN_LENGTH, GRAPH_PLACEMENT_RADIUS, GRAPH_MAX_MOVES)
    game = hexo_rs.GameState(config)
    for q, r in GRAPH_MOVES[:n_moves]:
        game.apply_move(q, r)
    return game


def test_rust_graph_request_matches_python_collation():
    """TQ2-W1: the MSG_FORWARD request bytes emitted by the REAL Rust client
    encoder (`encode_forward_request`, which `forward_graphs` calls) must parse
    via `_read_forward_body` into tensors identical to the same positions built
    through hexo_rs single-graph collation — pinning the graph wire across
    languages (the states fixtures pin the states wire; this pins the legacy one).
    """
    raw = _read_fixture("wire_graph_request.bin")
    magic, version, msg_type = struct.unpack("<IBB", raw[:6])
    assert magic == MAGIC
    assert version == VERSION
    assert msg_type == MSG_FORWARD

    rust_body = _read_forward_body(io.BytesIO(raw[6:]), expected_node_dim=NODE_DIM)

    # Same positions, built through the Python-called hexo_rs builder and
    # collated exactly like the Rust encoder lays out the wire body.
    games = [_replay_graph(k) for k in GRAPH_POINTS]
    py_body = _read_forward_body(
        io.BytesIO(_collate_graph_body(games, NODE_DIM)), expected_node_dim=NODE_DIM,
    )

    # Framing / scalar fields agree.
    for key in ("total_nodes", "total_edges", "num_graphs", "has_edge_attr",
                "node_dim"):
        assert rust_body[key] == py_body[key], f"body field {key!r}"

    # Tensors equal through the unmodified _prepare_tensors.
    cpu = torch.device("cpu")
    r_tensors, r_real_n = _prepare_tensors(rust_body, cpu, None, padded=False)
    p_tensors, p_real_n = _prepare_tensors(py_body, cpu, None, padded=False)
    assert r_real_n == p_real_n == len(GRAPH_POINTS)
    assert len(r_tensors) == len(p_tensors)
    for i, (rv, pv) in enumerate(zip(r_tensors, p_tensors)):
        if isinstance(pv, int):  # num_graphs
            assert rv == pv, f"tensor slot {i} (num_graphs) differs"
            continue
        assert rv.dtype == pv.dtype and rv.shape == pv.shape, f"tensor slot {i}"
        assert torch.equal(rv, pv), f"tensor slot {i} values differ"


def test_server_rebuild_hashes_match_rust_client_hashes():
    """End-to-end order guard: the server parses the Rust-encoded request,
    rebuilds the graphs, and its per-graph FNV-1a legal-coord hashes must
    equal the hashes the Rust CLIENT computed from its own legal_moves()
    snapshots (wire_states_legal_hashes.bin)."""
    raw = _read_fixture()
    result = _read_forward_states_body(io.BytesIO(raw[6:]), NODE_DIM)
    assert result is not None, "non-empty request must not parse as a probe"
    body, server_hashes = result
    assert body["num_graphs"] == len(SNAPSHOT_POINTS)
    assert body["node_dim"] == NODE_DIM

    hash_bytes = _read_fixture("wire_states_legal_hashes.bin")
    client_hashes = list(
        struct.unpack(f"<{len(hash_bytes) // 8}Q", hash_bytes)
    )
    assert len(client_hashes) == len(SNAPSHOT_POINTS)
    assert list(server_hashes) == client_hashes, (
        "legal-order FNV divergence between the Rust client snapshot and the "
        "server rebuild — the states wire's order guard would trip"
    )
