#!/usr/bin/env python
"""Find a strong checkpoint with a bounded coarse-to-fine search.

An exact maximum cannot be found without evaluating every checkpoint unless
checkpoint strength is assumed to be monotone or unimodal. Neither assumption
is generally valid during training, so this script instead reports the best
checkpoint found under an explicit head-to-head evaluation budget.

The search has three stages:

1. Screen evenly spaced checkpoints against one fixed baseline.
2. Spend the remaining screening budget refining intervals adjacent to the
   strongest screened evidence.
3. Let the other finalists challenge the screened incumbent directly.

All screening matches use the same fixed baseline as side B, the same seed, and
openings generated by that baseline. ``run_head_to_head`` replays every sampled
opening with colours swapped, so checkpoint estimates share replayable paired
openings instead of independent opening noise.

The complete search record is written atomically after every comparison. It
contains checkpoint hashes, configuration, match summaries, and the exact
screening opening bank. ``elo_ladder.txt`` remains as a compact human-readable
view, but its heading makes clear that it covers only screened checkpoints.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import re
import tempfile
from dataclasses import asdict, dataclass, replace
from pathlib import Path
from typing import Any, Literal


_CHECKPOINT_RE = re.compile(r"checkpoint_(\d+)\.pt")
_RESULT_FILENAME = "strongest_checkpoint_search.json"
_LADDER_FILENAME = "elo_ladder.txt"
_RESULT_VERSION = 1


@dataclass(frozen=True)
class Config:
    """Arguments forwarded to :func:`hexo_a0.head_to_head.run_head_to_head`."""

    win_length: int = 6
    radius: int = 8
    max_moves: int = 400
    mcts_sims: int = 24
    mcts_m_actions: int = 8
    device_str: str = "cuda"
    sprt_s0: float = 0.50
    sprt_s1: float = 0.55
    sprt_alpha: float = 0.05
    sprt_beta: float = 0.05
    window_size: int | None = None
    pair_variance: float = 0.5
    max_games: int = 1000
    seed: int = 0
    opening_plies: int = 6
    opening_temperature: float = 1.0
    opening_generator: Literal["alternate", "a", "b", "champion"] = "champion"
    disable_forcing_solver: bool = False


@dataclass(frozen=True)
class SearchConfig:
    """Budget and sampling controls for the coarse-to-fine search."""

    max_evaluations: int = 12
    coarse_count: int = 6
    finalists: int = 3


@dataclass(frozen=True)
class Checkpoint:
    path: Path
    step: int


def checkpoint_step_from_name(path: str | Path) -> int | None:
    """Return the exact ``checkpoint_<step>.pt`` step, if present."""

    match = _CHECKPOINT_RE.fullmatch(Path(path).name)
    return int(match.group(1)) if match else None


def _checkpoint_step_from_metadata(path: Path) -> int | None:
    """Read ``train_steps``/``iteration`` for a non-numbered baseline."""

    import torch

    try:
        checkpoint = torch.load(path, map_location="cpu", weights_only=True)
    except Exception:
        checkpoint = torch.load(path, map_location="cpu", weights_only=False)
    if not isinstance(checkpoint, dict):
        return None
    for key in ("train_steps", "iteration"):
        value = checkpoint.get(key)
        if isinstance(value, int):
            return value
        if isinstance(value, str) and value.isdigit():
            return int(value)
    return None


def checkpoint_step(path: str | Path, supplied_step: int | None = None) -> int:
    """Resolve a checkpoint step from an override, filename, or metadata."""

    if supplied_step is not None:
        if supplied_step < 0:
            raise ValueError("baseline_step must be non-negative")
        filename_step = checkpoint_step_from_name(path)
        if filename_step is not None and filename_step != supplied_step:
            raise ValueError(
                f"baseline_step={supplied_step} conflicts with step "
                f"{filename_step} in {Path(path).name}"
            )
        return supplied_step
    checkpoint_path = Path(path)
    filename_step = checkpoint_step_from_name(checkpoint_path)
    if filename_step is not None:
        return filename_step
    metadata_step = _checkpoint_step_from_metadata(checkpoint_path)
    if metadata_step is not None:
        return metadata_step
    raise ValueError(
        f"Cannot determine training step for baseline {checkpoint_path}. "
        "Use a checkpoint_<step>.pt file or pass --baseline-step."
    )


def get_checkpoint_files(directory: str | Path) -> list[str]:
    """Return direct, complete ``checkpoint_<step>.pt`` files in a directory."""

    root = Path(directory)
    return [
        str(path)
        for path in root.iterdir()
        if path.is_file() and checkpoint_step_from_name(path) is not None
    ]


def get_newer_checkpoints(
    checkpoint_files: list[str],
    baseline_checkpoint: str | Path,
    baseline_step: int | None = None,
) -> list[str]:
    """Return checkpoints with a numeric training step above the baseline."""

    minimum = checkpoint_step(baseline_checkpoint, baseline_step)
    newer = [
        path
        for path in checkpoint_files
        if (step := checkpoint_step_from_name(path)) is not None and step > minimum
    ]
    return sorted(newer, key=lambda path: checkpoint_step_from_name(path) or -1)


def discover_checkpoints(
    directory: str | Path,
    baseline_checkpoint: str | Path,
    baseline_step: int | None = None,
) -> tuple[Path, int, list[Checkpoint]]:
    """Validate paths and return strictly post-baseline checkpoints by step."""

    root = Path(directory).expanduser().resolve()
    baseline = Path(baseline_checkpoint).expanduser().resolve()
    if not root.is_dir():
        raise NotADirectoryError(f"Checkpoint directory does not exist: {root}")
    if not baseline.is_file():
        raise FileNotFoundError(f"Baseline checkpoint does not exist: {baseline}")

    minimum = checkpoint_step(baseline, baseline_step)
    candidates: list[Checkpoint] = []
    steps: dict[int, Path] = {}
    resolved_paths: dict[Path, int] = {}
    for raw_path in get_checkpoint_files(root):
        step = checkpoint_step_from_name(raw_path)
        assert step is not None
        path = Path(raw_path).resolve()
        if step <= minimum:
            continue
        if step in steps:
            raise ValueError(
                f"Duplicate checkpoint step {step}: {steps[step]} and {path}"
            )
        if path in resolved_paths:
            raise ValueError(
                f"Checkpoint steps {resolved_paths[path]} and {step} resolve to "
                f"the same file: {path}"
            )
        steps[step] = path
        resolved_paths[path] = step
        candidates.append(Checkpoint(path=path, step=step))
    candidates.sort(key=lambda checkpoint: checkpoint.step)
    return baseline, minimum, candidates


def run_head_to_head(checkpoint_a: Path, checkpoint_b: Path, config: Config) -> dict:
    from hexo_a0.head_to_head import run_head_to_head as hexo_run_head_to_head

    return hexo_run_head_to_head(checkpoint_a, checkpoint_b, **asdict(config))


def validate_config(config: Config, search_config: SearchConfig) -> None:
    """Reject settings that break the search's paired/reproducible contract."""

    if search_config.max_evaluations <= 0:
        raise ValueError("max_evaluations must be positive")
    if search_config.coarse_count <= 0:
        raise ValueError("coarse_count must be positive")
    if search_config.finalists <= 0:
        raise ValueError("finalists must be positive")
    if config.max_games <= 0 or config.max_games % 2:
        raise ValueError("max_games must be a positive even number")
    if config.window_size is not None and (
        config.window_size <= 0 or config.window_size % 2
    ):
        raise ValueError("window_size must be None or a positive even number")
    if config.opening_plies <= 0:
        raise ValueError("opening_plies must be positive for fixed paired openings")
    if config.opening_generator not in {"b", "champion"}:
        raise ValueError(
            "opening_generator must be 'b' or 'champion' so every screening "
            "match uses the fixed baseline's opening policy"
        )
    if config.seed is None:
        raise ValueError("seed must be set for a reproducible search")
    if not (0.0 < config.sprt_s0 < config.sprt_s1 < 1.0):
        raise ValueError("SPRT scores must satisfy 0 < s0 < s1 < 1")
    if not (0.0 < config.sprt_alpha < 1.0):
        raise ValueError("sprt_alpha must be between 0 and 1")
    if not (0.0 < config.sprt_beta < 1.0):
        raise ValueError("sprt_beta must be between 0 and 1")
    if config.pair_variance <= 0:
        raise ValueError("pair_variance must be positive")


def evenly_spaced_indices(candidate_count: int, sample_count: int) -> list[int]:
    """Choose unique endpoints and evenly spaced interior candidate indices."""

    if candidate_count <= 0 or sample_count <= 0:
        return []
    sample_count = min(candidate_count, sample_count)
    if sample_count == 1:
        return [candidate_count - 1]
    last = candidate_count - 1
    return [round(index * last / (sample_count - 1)) for index in range(sample_count)]


def _result_rank_key(comparison: dict[str, Any]) -> tuple[float, float, int, int]:
    """Rank screens by conservative Elo evidence, then estimate and recency."""

    result = comparison["result"]
    elo = float(result["elo_diff"])
    lower = float(result.get("elo_ci_lo", elo))
    games = int(result.get("games", 0))
    step = int(comparison["candidate"]["step"])
    return lower, elo, games, step


def choose_refinement_index(
    evaluated: dict[int, dict[str, Any]],
) -> int | None:
    """Return the midpoint of the most promising still-unresolved interval."""

    ordered = sorted(evaluated)
    intervals: list[tuple[tuple[float, float, int, int], int, int, int]] = []
    for left, right in zip(ordered, ordered[1:]):
        gap = right - left
        if gap <= 1:
            continue
        endpoint_evidence = max(
            _result_rank_key(evaluated[left]),
            _result_rank_key(evaluated[right]),
        )
        # Prefer intervals touching stronger evidence, then wider intervals,
        # then the later interval as a deterministic final tie-breaker.
        intervals.append((endpoint_evidence, gap, right, (left + right) // 2))
    if not intervals:
        return None
    return max(intervals)[-1]


def _screen_and_playoff_budgets(
    candidate_count: int,
    search_config: SearchConfig,
) -> tuple[int, int]:
    """Reserve direct-finalist matches without exceeding the hard budget."""

    total = min(search_config.max_evaluations, 2 * candidate_count - 1)
    finalist_count = min(
        search_config.finalists,
        candidate_count,
        (total + 1) // 2,
    )
    playoff_budget = max(0, finalist_count - 1)
    screen_budget = min(candidate_count, total - playoff_budget)
    playoff_budget = min(playoff_budget, max(0, screen_budget - 1))
    return screen_budget, playoff_budget


def _file_fingerprint(path: Path) -> dict[str, int]:
    stat = path.stat()
    return {
        "device": stat.st_dev,
        "inode": stat.st_ino,
        "size": stat.st_size,
        "mtime_ns": stat.st_mtime_ns,
    }


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as checkpoint_file:
        for block in iter(lambda: checkpoint_file.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _checkpoint_identity(
    checkpoint: Checkpoint,
    cache: dict[Path, dict[str, Any]],
) -> dict[str, Any]:
    """Hash once and reject a checkpoint that changes during the search."""

    current_fingerprint = _file_fingerprint(checkpoint.path)
    prior = cache.get(checkpoint.path)
    if prior is not None:
        if prior["fingerprint"] != current_fingerprint:
            raise RuntimeError(f"Checkpoint changed during search: {checkpoint.path}")
        return prior
    identity = {
        "path": str(checkpoint.path),
        "step": checkpoint.step,
        "sha256": _sha256(checkpoint.path),
        "fingerprint": current_fingerprint,
    }
    cache[checkpoint.path] = identity
    return identity


def _atomic_write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f"{path.name}.", suffix=".tmp", dir=path.parent
    )
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as output_file:
            json.dump(payload, output_file, indent=2, sort_keys=True, default=str)
            output_file.write("\n")
        temporary_path.replace(path)
    except Exception:
        try:
            temporary_path.unlink()
        except OSError:
            pass
        raise


def _normalise_result(result: dict[str, Any]) -> dict[str, Any]:
    if not isinstance(result, dict):
        raise TypeError("head-to-head result must be a dictionary")
    winner = result.get("winner")
    if winner not in {"A", "B", "inconclusive"}:
        raise ValueError(f"Unexpected head-to-head winner label: {winner!r}")
    decision = result.get("decision")
    expected_decision = {
        "A": "accept_h1",
        "B": "reject_h1",
        "inconclusive": "continue",
    }[winner]
    if decision is not None and decision != expected_decision:
        raise ValueError(
            f"Inconsistent head-to-head outcome: winner={winner!r}, "
            f"decision={decision!r}"
        )
    try:
        elo = float(result["elo_diff"])
    except (KeyError, TypeError, ValueError) as error:
        raise ValueError("head-to-head result has no numeric elo_diff") from error
    if not math.isfinite(elo):
        raise ValueError("head-to-head elo_diff must be finite")
    normalised = dict(result)
    normalised["elo_diff"] = elo
    return normalised


def _opening_pairs(result: dict[str, Any]) -> list[Any]:
    per_game = result.get("per_game_opening")
    if not per_game:
        return []
    return list(per_game[::2])


def _update_screening_opening_bank(
    state: dict[str, Any], result: dict[str, Any]
) -> None:
    """Verify that all screens use prefixes of one exact opening bank."""

    openings = _opening_pairs(result)
    if not openings:
        raise ValueError(
            "head-to-head result did not include paired openings; fixed-opening "
            "screening requires opening_plies > 0"
        )
    reference = state.get("screening_opening_bank", [])
    shared = min(len(reference), len(openings))
    if reference[:shared] != openings[:shared]:
        raise RuntimeError(
            "Screening opening banks differ despite a fixed baseline and seed"
        )
    if len(openings) > len(reference):
        state["screening_opening_bank"] = openings


def _write_ladder(
    path: Path,
    baseline: Checkpoint,
    comparisons: list[dict[str, Any]],
    selected: Checkpoint | None = None,
) -> None:
    screens = [item for item in comparisons if item["stage"] == "screen"]
    screens.sort(key=_result_rank_key, reverse=True)
    lines = [
        "# Best checkpoint found under a bounded coarse-to-fine search.",
        "# Elo values below are independent A-B estimates versus the fixed baseline.",
        "Checkpoint\tStep\tElo\tElo 95% CI\tDecision\tGames",
    ]
    for comparison in screens:
        result = comparison["result"]
        elo = float(result["elo_diff"])
        ci_low = float(result.get("elo_ci_lo", elo))
        ci_high = float(result.get("elo_ci_hi", elo))
        lines.append(
            f"{comparison['candidate']['path']}\t"
            f"{comparison['candidate']['step']}\t{elo:+.2f}\t"
            f"[{ci_low:+.2f}, {ci_high:+.2f}]\t"
            f"{result.get('decision', result['winner'])}\t"
            f"{result.get('games', '?')}"
        )
    lines.append(
        f"{baseline.path}\t{baseline.step}\t+0.00\t[anchor]\tbaseline\t-"
    )
    if selected is not None:
        lines.extend(
            [
                "",
                f"# Selected checkpoint: {selected.path}",
                f"# Selected step: {selected.step}",
            ]
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _comparison_summary(result: dict[str, Any]) -> str:
    elo = float(result["elo_diff"])
    return (
        f"decision={result.get('decision', result['winner'])}, "
        f"label={result['winner']}, Elo(A-B)={elo:+.1f}, "
        f"games={result.get('games', '?')}"
    )


def _evaluate_comparison(
    *,
    stage: Literal["screen", "playoff"],
    candidate: Checkpoint,
    opponent: Checkpoint,
    config: Config,
    state: dict[str, Any],
    result_path: Path,
    ladder_path: Path,
    baseline: Checkpoint,
    identity_cache: dict[Path, dict[str, Any]],
) -> dict[str, Any]:
    if candidate.path == opponent.path:
        raise RuntimeError(f"Refusing self-comparison for {candidate.path}")

    print(
        f"[{stage}] comparing step {candidate.step} (A) with "
        f"step {opponent.step} (B)...",
        flush=True,
    )
    candidate_identity = _checkpoint_identity(candidate, identity_cache)
    opponent_identity = _checkpoint_identity(opponent, identity_cache)
    candidate_before = dict(candidate_identity["fingerprint"])
    opponent_before = dict(opponent_identity["fingerprint"])

    try:
        result = _normalise_result(
            run_head_to_head(candidate.path, opponent.path, config)
        )
        if _file_fingerprint(candidate.path) != candidate_before:
            raise RuntimeError(
                f"Candidate checkpoint changed during comparison: {candidate.path}"
            )
        if _file_fingerprint(opponent.path) != opponent_before:
            raise RuntimeError(
                f"Opponent checkpoint changed during comparison: {opponent.path}"
            )
        if stage == "screen":
            _update_screening_opening_bank(state, result)
    except Exception as error:
        state["status"] = "failed"
        state["error"] = {
            "type": type(error).__name__,
            "message": str(error),
            "stage": stage,
            "candidate": str(candidate.path),
            "opponent": str(opponent.path),
        }
        _atomic_write_json(result_path, state)
        _write_ladder(ladder_path, baseline, state["comparisons"], selected=None)
        raise

    comparison = {
        "stage": stage,
        "candidate": candidate_identity,
        "opponent": opponent_identity,
        "seed": config.seed,
        "result": result,
    }
    state["comparisons"].append(comparison)
    _atomic_write_json(result_path, state)
    _write_ladder(ladder_path, baseline, state["comparisons"], selected=None)
    print(f"[{stage}] {_comparison_summary(result)}", flush=True)
    return comparison


def find_strongest_checkpoint(
    directory: str | Path | None,
    baseline_checkpoint: str | Path,
    config: Config,
    search_config: SearchConfig | None = None,
    *,
    baseline_step: int | None = None,
    result_path: str | Path | None = None,
    ladder_path: str | Path | None = None,
) -> dict[str, Any]:
    """Run the bounded search and return its complete structured record."""

    search_config = search_config or SearchConfig()
    validate_config(config, search_config)

    baseline_input = Path(baseline_checkpoint).expanduser()
    search_directory = (
        Path(directory).expanduser()
        if directory is not None
        else baseline_input.resolve().parent
    )
    baseline_path, minimum_step, candidates = discover_checkpoints(
        search_directory,
        baseline_input,
        baseline_step,
    )
    baseline = Checkpoint(path=baseline_path, step=minimum_step)
    root = search_directory.resolve()
    output_path = (
        Path(result_path).expanduser().resolve()
        if result_path is not None
        else root / _RESULT_FILENAME
    )
    text_path = (
        Path(ladder_path).expanduser().resolve()
        if ladder_path is not None
        else root / _LADDER_FILENAME
    )
    protected_paths = {baseline.path, *(candidate.path for candidate in candidates)}
    if output_path == text_path:
        raise ValueError("result_file and ladder_file must be different paths")
    for label, artifact_path in (
        ("result_file", output_path),
        ("ladder_file", text_path),
    ):
        if artifact_path.suffix == ".pt" or artifact_path in protected_paths:
            raise ValueError(
                f"Refusing to use checkpoint path as {label}: {artifact_path}"
            )

    identity_cache: dict[Path, dict[str, Any]] = {}
    baseline_identity = _checkpoint_identity(baseline, identity_cache)
    screen_budget, playoff_budget = (
        _screen_and_playoff_budgets(len(candidates), search_config)
        if candidates
        else (0, 0)
    )
    state: dict[str, Any] = {
        "version": _RESULT_VERSION,
        "status": "running" if candidates else "no_candidates",
        "method": "budgeted_coarse_to_fine",
        "claim": "best checkpoint found under the configured evaluation budget",
        "selection_metric": "screening Elo 95% lower bound, then Elo point estimate",
        "directory": str(root),
        "baseline": baseline_identity,
        "candidates": [
            {"path": str(candidate.path), "step": candidate.step}
            for candidate in candidates
        ],
        "match_config": asdict(config),
        "search_config": asdict(search_config),
        "budget": {
            "screen_matches": screen_budget,
            "playoff_matches": playoff_budget,
            "total_matches": screen_budget + playoff_budget,
        },
        "screening_protocol": {
            "fixed_opponent": str(baseline.path),
            "fixed_seed": config.seed,
            "opening_generator": config.opening_generator,
            "paired_colour_swap": True,
        },
        "screening_opening_bank": [],
        "comparisons": [],
        "selected_checkpoint": baseline_identity if not candidates else None,
    }
    _atomic_write_json(output_path, state)

    if not candidates:
        _write_ladder(text_path, baseline, [], selected=baseline)
        print("No checkpoint steps were found above the baseline step.")
        return state

    candidate_by_path = {candidate.path: candidate for candidate in candidates}
    initial_count = min(
        screen_budget,
        max(2 if screen_budget > 1 else 1, search_config.coarse_count),
    )
    initial_indices = evenly_spaced_indices(len(candidates), initial_count)
    # Evaluate the newest endpoint first so an interrupted coarse pass still
    # leaves the most operationally relevant comparison in the state file.
    initial_order = [initial_indices[-1], *initial_indices[:-1]]
    evaluated: dict[int, dict[str, Any]] = {}
    for index in initial_order:
        comparison = _evaluate_comparison(
            stage="screen",
            candidate=candidates[index],
            opponent=baseline,
            config=config,
            state=state,
            result_path=output_path,
            ladder_path=text_path,
            baseline=baseline,
            identity_cache=identity_cache,
        )
        evaluated[index] = comparison

    while len(evaluated) < screen_budget:
        index = choose_refinement_index(evaluated)
        if index is None:
            break
        comparison = _evaluate_comparison(
            stage="screen",
            candidate=candidates[index],
            opponent=baseline,
            config=config,
            state=state,
            result_path=output_path,
            ladder_path=text_path,
            baseline=baseline,
            identity_cache=identity_cache,
        )
        evaluated[index] = comparison

    ranked_screens = sorted(
        evaluated.values(), key=_result_rank_key, reverse=True
    )
    accepted_screens = [
        comparison
        for comparison in ranked_screens
        if comparison["result"]["winner"] == "A"
    ]
    incumbent = (
        candidate_by_path[Path(accepted_screens[0]["candidate"]["path"])]
        if accepted_screens
        else baseline
    )
    challengers = [
        comparison
        for comparison in ranked_screens
        if Path(comparison["candidate"]["path"]) != incumbent.path
    ][:playoff_budget]
    for playoff_index, challenger_comparison in enumerate(challengers):
        challenger = candidate_by_path[
            Path(challenger_comparison["candidate"]["path"])
        ]
        playoff_config = replace(config, seed=config.seed + 1_000_000 + playoff_index)
        comparison = _evaluate_comparison(
            stage="playoff",
            candidate=challenger,
            opponent=incumbent,
            config=playoff_config,
            state=state,
            result_path=output_path,
            ladder_path=text_path,
            baseline=baseline,
            identity_cache=identity_cache,
        )
        # This is deliberately conservative: accept_h1/A displaces the
        # incumbent. reject_h1/B means the challenger did not establish the
        # configured s1 advantage; inconclusive is retained as inconclusive.
        if comparison["result"]["winner"] == "A":
            incumbent = challenger

    state["status"] = "complete"
    state["selected_checkpoint"] = _checkpoint_identity(incumbent, identity_cache)
    state["selection_basis"] = (
        "The baseline remained incumbent unless a candidate established the "
        "configured SPRT H1 advantage. Among accepted candidates, conservative "
        "screening Elo selected the incumbent; a finalist displaced it only by "
        "establishing H1 in direct play."
    )
    _atomic_write_json(output_path, state)
    _write_ladder(
        text_path,
        baseline,
        state["comparisons"],
        selected=incumbent,
    )
    print(
        f"Selected step {incumbent.step}: {incumbent.path}\n"
        f"Structured result: {output_path}\n"
        f"Screening ladder: {text_path}",
        flush=True,
    )
    return state


def parse_arguments(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Find a strong checkpoint with a bounded coarse-to-fine search. "
            "The result is best-found-under-budget, not a guaranteed maximum."
        )
    )
    parser.add_argument(
        "baseline_checkpoint",
        type=Path,
        help="Fixed baseline checkpoint used for every screening comparison.",
    )
    parser.add_argument(
        "--directory",
        type=Path,
        default=None,
        help="Candidate directory (default: baseline checkpoint's directory).",
    )
    parser.add_argument(
        "--baseline-step",
        type=int,
        default=None,
        help="Training step override for a non-numbered baseline checkpoint.",
    )
    parser.add_argument(
        "--max-evaluations",
        type=int,
        default=12,
        help="Hard cap on screening plus playoff head-to-head matches (default 12).",
    )
    parser.add_argument(
        "--coarse-count",
        type=int,
        default=6,
        help="Initial evenly spaced screening sample (default 6).",
    )
    parser.add_argument(
        "--finalists",
        type=int,
        default=3,
        help="Maximum screened contenders retained for direct playoffs (default 3).",
    )
    parser.add_argument(
        "--result-file",
        type=Path,
        default=None,
        help=f"Structured JSON output (default: candidate directory/{_RESULT_FILENAME}).",
    )
    parser.add_argument(
        "--ladder-file",
        type=Path,
        default=None,
        help=f"Readable screening ladder (default: candidate directory/{_LADDER_FILENAME}).",
    )

    parser.add_argument("--win-length", type=int, default=6)
    parser.add_argument("--radius", type=int, default=8)
    parser.add_argument("--max-moves", type=int, default=400)
    parser.add_argument("--mcts-sims", type=int, default=24)
    parser.add_argument("--mcts-m-actions", type=int, default=8)
    parser.add_argument("--device", dest="device_str", default="cuda")
    parser.add_argument("--sprt-s0", type=float, default=0.50)
    parser.add_argument("--sprt-s1", type=float, default=0.55)
    parser.add_argument("--sprt-alpha", type=float, default=0.05)
    parser.add_argument("--sprt-beta", type=float, default=0.05)
    parser.add_argument(
        "--window-size",
        type=int,
        default=0,
        help="Even sliding-window game count; 0 uses all games.",
    )
    parser.add_argument("--pair-variance", type=float, default=0.5)
    parser.add_argument("--max-games", type=int, default=1000)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--opening-plies", type=int, default=6)
    parser.add_argument("--opening-temperature", type=float, default=1.0)
    parser.add_argument(
        "--opening-generator",
        choices=["b", "champion"],
        default="champion",
        help="Fixed B/baseline opening policy used by every screen.",
    )
    parser.add_argument("--disable-forcing-solver", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_arguments(argv)
    config = Config(
        win_length=args.win_length,
        radius=args.radius,
        max_moves=args.max_moves,
        mcts_sims=args.mcts_sims,
        mcts_m_actions=args.mcts_m_actions,
        device_str=args.device_str,
        sprt_s0=args.sprt_s0,
        sprt_s1=args.sprt_s1,
        sprt_alpha=args.sprt_alpha,
        sprt_beta=args.sprt_beta,
        window_size=args.window_size or None,
        pair_variance=args.pair_variance,
        max_games=args.max_games,
        seed=args.seed,
        opening_plies=args.opening_plies,
        opening_temperature=args.opening_temperature,
        opening_generator=args.opening_generator,
        disable_forcing_solver=args.disable_forcing_solver,
    )
    search_config = SearchConfig(
        max_evaluations=args.max_evaluations,
        coarse_count=args.coarse_count,
        finalists=args.finalists,
    )
    find_strongest_checkpoint(
        args.directory,
        args.baseline_checkpoint,
        config,
        search_config,
        baseline_step=args.baseline_step,
        result_path=args.result_file,
        ladder_path=args.ladder_file,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
